/*
 * MainFrame.java
 *
 * Created on 22 gennaio 2008, 10.43
 */
package gui;

import abstractlayer.Artista;
import abstractlayer.Cliente;
import abstractlayer.Fattura;
import abstractlayer.Opera;
import daorules.ClienteDAO;
import daorules.*;
import temporarymain.*;
import exceptions.ArchivioNonTrovatoException;
import exceptions.RecordNonPresenteException;
import java.sql.Connection;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import msaccessimpl.MSAccessDAOFactory;
import abstractlayer.Regione;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author  Mir1
 */
public class MainFrame extends javax.swing.JFrame {

    /* necessari per la connessione con il DB*/
    Connection connection;
    String cod;
    ArtistaDAO artistaDAO;
    ClienteDAO clienteDAO;
    FatturaDAO fatturaDAO;
    OperaDAO operaDAO;
    String columnsCli[] = {"ID", "Cognome / Rag.Soc", "Nome / Rag.Soc. 2", "Indirizzo", "N° Civico", "Città", "Provincia", "regione", "Stato", "Tel1", "Tel2", "Cell1", "Cell2", "Mail1", "Mail2", "CF / P.IVA", "Note"};
    String columnsOpere[] = {"Codice Opera", "Titolo opera", "Artista", "Tecnica", "Dimensioni", "Tipo", "Venduto", "Foto", "Numero Fattura", "Anno Fattura", "Prezzo"};
    String columnsArtisti[] = {"Codice Artista", "Cognome", "Nome", "Note biografiche"};
    String columnsFatture[] = {"Numero", "ID Cliente", "Data", "Sconto", "Totale"};
    DefaultTableModel modelCli;
    DefaultTableModel modelOpere;
    DefaultTableModel modelArtisti;
    DefaultTableModel modelFatture;
    Artista ar;
    Opera opera;
    Cliente cli;
    Fattura fat;
    String artistaCod;
    String operaCod;
    Vector<Regione> regioniSel = new Vector<Regione>();
    Vector<Cliente> cliPerCog = new Vector<Cliente>();
    Vector<Cliente> cliPerReg = new Vector<Cliente>();
    Vector<Fattura> fattPerCliCog = new Vector<Fattura>();
    Vector<Fattura> fattPerCliReg = new Vector<Fattura>();
    Vector<Opera> operePerCliCog = new Vector<Opera>();
    Vector<Opera> operePerCliReg = new Vector<Opera>();
    DefaultListModel lModel = new DefaultListModel();
    private Cliente cliFattOpera;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        DAOFactory msaccessFactory =
                (MSAccessDAOFactory) DAOFactory.getDAOFactory(DAOFactory.MSACCESS);
        try {
            connection = msaccessFactory.getConnection();
        } catch (ArchivioNonTrovatoException ante) {
            System.err.println(ante);
        }
        // Create DAOs
        clienteDAO = msaccessFactory.getClienteDAO();
        artistaDAO = msaccessFactory.getArtistaDAO();
        fatturaDAO = msaccessFactory.getFatturaDAO();
        operaDAO = msaccessFactory.getOperaDAO();
        modelCli = new DefaultTableModel();
        modelOpere = new DefaultTableModel();
        modelArtisti = new DefaultTableModel();
        modelFatture = new DefaultTableModel();

        fillColonne(modelArtisti, columnsArtisti);
        fillColonne(modelCli, columnsCli);
        fillColonne(modelOpere, columnsOpere);
        fillColonne(modelFatture, columnsFatture);
        fillTabCli();
        fillTabOpere();
        fillTabArtisti();
        fillTabFatture();
        txtPaneArtisti.setText("Elenco completo artisti");
        txtPaneClienti.setText("Elenco completo clienti");
        txtPaneOpere.setText("Elenco completo opere");
        txtPaneFattura.setText("Elenco completo fatture");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtPaneClienti = new javax.swing.JTextPane();
        buttonResClienti = new javax.swing.JButton();
        buttonResAllClienti = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCogCod = new javax.swing.JTextField();
        buttClienteCog = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        buttClienteReg = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        buttClienteRegAdd = new javax.swing.JButton();
        buttClienteRegDel = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listRegSel = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtPaneOpere = new javax.swing.JTextPane();
        buttonResOpere = new javax.swing.JButton();
        buttonResAllOpere = new javax.swing.JButton();
        txtOperaCod = new javax.swing.JTextField();
        buttOperaCod = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtArtistaCod = new javax.swing.JTextField();
        buttArtistaCod = new javax.swing.JButton();
        buttonResArtista = new javax.swing.JButton();
        buttonResAllArtista = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPaneArtisti = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtFatturaCod = new javax.swing.JTextField();
        buttFatturaCod = new javax.swing.JButton();
        buttonResFatture = new javax.swing.JButton();
        buttonResAllArtista1 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtPaneFattura = new javax.swing.JTextPane();
        buttFatturaCod1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFatturaCod1 = new javax.swing.JTextField();
        buttFatturaCod2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtFatturaCod2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        jScrollPane7.setViewportView(txtPaneClienti);

        buttonResClienti.setText("Reset"); // NOI18N
        buttonResClienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResClientiActionPerformed(evt);
            }
        });

        buttonResAllClienti.setText("Reset All"); // NOI18N
        buttonResAllClienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResAllClientiActionPerformed(evt);
            }
        });

        jLabel4.setText("Ricerca cliente per cognome :"); // NOI18N

        txtCogCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCogCodActionPerformed(evt);
            }
        });

        buttClienteCog.setText("Avvia Ricerca"); // NOI18N
        buttClienteCog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttClienteCogMouseEntered(evt);
            }
        });
        buttClienteCog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttClienteCogActionPerformed(evt);
            }
        });

        jLabel5.setText("Ricerca cliente per regione"); // NOI18N

        buttClienteReg.setText("Avvia Ricerca"); // NOI18N
        buttClienteReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttClienteRegMouseEntered(evt);
            }
        });
        buttClienteReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttClienteRegActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(Regione.values()));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        buttClienteRegAdd.setText("Aggiungi"); // NOI18N
        buttClienteRegAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttClienteRegAddMouseEntered(evt);
            }
        });
        buttClienteRegAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttClienteRegAddActionPerformed(evt);
            }
        });

        buttClienteRegDel.setText("Rimuovi"); // NOI18N
        buttClienteRegDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttClienteRegDelMouseEntered(evt);
            }
        });
        buttClienteRegDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttClienteRegDelActionPerformed(evt);
            }
        });

        listRegSel.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listRegSel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonResClienti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonResAllClienti)
                .addGap(59, 59, 59))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCogCod, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttClienteRegAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttClienteCog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttClienteRegDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttClienteReg)
                        .addGap(31, 31, 31)))
                .addGap(222, 222, 222))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonResClienti)
                        .addComponent(buttonResAllClienti))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(buttClienteCog)
                    .addComponent(txtCogCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttClienteReg))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttClienteRegAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttClienteRegDel)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clienti", jPanel1);

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setText("Ricerca opera per codice :"); // NOI18N

        jScrollPane6.setViewportView(txtPaneOpere);

        buttonResOpere.setText("Reset"); // NOI18N
        buttonResOpere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResOpereActionPerformed(evt);
            }
        });

        buttonResAllOpere.setText("Reset All"); // NOI18N
        buttonResAllOpere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResAllOpereActionPerformed(evt);
            }
        });

        txtOperaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOperaCodActionPerformed(evt);
            }
        });

        buttOperaCod.setText("Avvia Ricerca"); // NOI18N
        buttOperaCod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttOperaCodMouseEntered(evt);
            }
        });
        buttOperaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttOperaCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOperaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttOperaCod)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonResOpere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonResAllOpere)
                        .addGap(51, 51, 51))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonResOpere)
                        .addComponent(buttonResAllOpere))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOperaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buttOperaCod))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Opere", jPanel3);

        jTable3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setText("Ricerca artista per codice :"); // NOI18N

        txtArtistaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistaCodActionPerformed(evt);
            }
        });

        buttArtistaCod.setText("Avvia Ricerca"); // NOI18N
        buttArtistaCod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttArtistaCodMouseEntered(evt);
            }
        });
        buttArtistaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttArtistaCodActionPerformed(evt);
            }
        });

        buttonResArtista.setText("Reset"); // NOI18N
        buttonResArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResArtistaActionPerformed(evt);
            }
        });

        buttonResAllArtista.setText("Reset All"); // NOI18N
        buttonResAllArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResAllArtistaActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(txtPaneArtisti);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArtistaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttArtistaCod)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonResArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonResAllArtista)
                        .addGap(55, 55, 55))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonResArtista)
                        .addComponent(buttonResAllArtista))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtArtistaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttArtistaCod))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Artisti", jPanel4);

        jTable4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane8.setViewportView(jTable4);

        jLabel6.setText("Ricerca fattura per numero ed anno :"); // NOI18N

        txtFatturaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFatturaCodActionPerformed(evt);
            }
        });

        buttFatturaCod.setText("Avvia Ricerca"); // NOI18N
        buttFatturaCod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttFatturaCodMouseEntered(evt);
            }
        });
        buttFatturaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttFatturaCodActionPerformed(evt);
            }
        });

        buttonResFatture.setText("Reset"); // NOI18N
        buttonResFatture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResFattureActionPerformed(evt);
            }
        });

        buttonResAllArtista1.setText("Reset All"); // NOI18N
        buttonResAllArtista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResAllArtista1ActionPerformed(evt);
            }
        });

        jScrollPane9.setViewportView(txtPaneFattura);

        buttFatturaCod1.setText("Avvia Ricerca"); // NOI18N
        buttFatturaCod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttFatturaCod1MouseEntered(evt);
            }
        });
        buttFatturaCod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttFatturaCod1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Ricerca artista per codice :"); // NOI18N

        txtFatturaCod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFatturaCod1ActionPerformed(evt);
            }
        });

        buttFatturaCod2.setText("Avvia Ricerca"); // NOI18N
        buttFatturaCod2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttFatturaCod2MouseEntered(evt);
            }
        });
        buttFatturaCod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttFatturaCod2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Ricerca artista per codice :"); // NOI18N

        txtFatturaCod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFatturaCod2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFatturaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttFatturaCod)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonResFatture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonResAllArtista1)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFatturaCod1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttFatturaCod1)
                        .addContainerGap(445, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFatturaCod2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttFatturaCod2)
                        .addContainerGap(445, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonResFatture)
                        .addComponent(buttonResAllArtista1))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFatturaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttFatturaCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFatturaCod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttFatturaCod1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFatturaCod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttFatturaCod2))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fattura", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txtArtistaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistaCodActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtArtistaCodActionPerformed

    private void buttArtistaCodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttArtistaCodMouseEntered
  
}//GEN-LAST:event_buttArtistaCodMouseEntered

    
private void buttonResAllArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResAllArtistaActionPerformed
    resAll();
}//GEN-LAST:event_buttonResAllArtistaActionPerformed

private void buttArtistaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttArtistaCodActionPerformed
    artistaCod = txtArtistaCod.getText();
    if(!artistaCod.isEmpty()){
    try {
        int i = Integer.valueOf(artistaCod).intValue();
        ar = artistaDAO.findArtista(i);
    } catch (RecordNonPresenteException ex) {
        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    resetTable(modelArtisti);
    createRowArtisti(modelArtisti, ar);
    //ora mi occupo di popolare la tabella opere relativamente a questo artista
    Vector<Opera> op=operaDAO.selectOperaPerArtista(ar);
    resetTable(modelOpere);
    scanOpere(modelOpere,op);
    jTable2.setModel(modelOpere);
    txtPaneArtisti.setText("Ricerca effettuata per l'artista avente codice:" + artistaCod);
    txtPaneOpere.setText("Ricerca delle opere relative all'artista :" + ar.getCognome() + " " + ar.getNome());}
}//GEN-LAST:event_buttArtistaCodActionPerformed

private void buttonResArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResArtistaActionPerformed
    resetTable(modelArtisti);
    fillTabArtisti();
    txtPaneArtisti.setText("Elenco completo artisti");
}//GEN-LAST:event_buttonResArtistaActionPerformed

private void buttonResOpereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResOpereActionPerformed
    resetTable(modelOpere);
    fillTabOpere();
    txtPaneOpere.setText("Elenco completo opere");
}//GEN-LAST:event_buttonResOpereActionPerformed

private void buttonResAllOpereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResAllOpereActionPerformed
    resAll();
}//GEN-LAST:event_buttonResAllOpereActionPerformed

private void txtOperaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOperaCodActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtOperaCodActionPerformed

private void buttOperaCodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttOperaCodMouseEntered
    // TODO add your handling code here:
}//GEN-LAST:event_buttOperaCodMouseEntered

private void buttOperaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttOperaCodActionPerformed
    operaCod = txtOperaCod.getText();
    if (!operaCod.isEmpty()) {
        try {
            opera = operaDAO.findOpera(operaCod);
        } catch (RecordNonPresenteException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        resetTable(modelOpere);
        createRowOpere(modelOpere, opera);
        txtPaneOpere.setText("Ricerca effettuata per l'opera avente codice : " + operaCod + " Titolo : \"" + opera.getTitolo() + "\"");
        // ora svolgo la ricerca incrociata sui clienti cui l'opera è eventualmente legata tramite fattura
        if (opera.isVenduto()) {
            //cliFattOpera = opera.getFattura().getCliente();
            resetTable(modelCli);
            createRowClienti(modelCli, cliFattOpera);
            txtPaneClienti.setText("Cliente che ha acquistato l'opera: \"" + opera.getTitolo() + "\" dell'autore: " + opera.getArtista().getCognome() + " " + opera.getArtista().getNome());
        } else {
            txtPaneClienti.setText("Opera non ancora venduta, mostro tutti i clienti");
        }
    }
}//GEN-LAST:event_buttOperaCodActionPerformed

private void buttonResClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResClientiActionPerformed
    resetTable(modelCli);
    fillTabCli();
    txtPaneClienti.setText("Elenco completo clienti");
}//GEN-LAST:event_buttonResClientiActionPerformed

private void buttonResAllClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResAllClientiActionPerformed
    resAll();
}//GEN-LAST:event_buttonResAllClientiActionPerformed

private void txtCogCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCogCodActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtCogCodActionPerformed

private void buttClienteCogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttClienteCogMouseEntered
    // TODO add your handling code here:
}//GEN-LAST:event_buttClienteCogMouseEntered

private void buttClienteCogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttClienteCogActionPerformed
    String cliCog =txtCogCod.getText();
    cliPerCog.clear();
    if(!cliCog.isEmpty()){
    cliPerCog = clienteDAO.selectClientiPerStringa(cliCog);
    resetTable(modelCli);
    scanClienti(modelCli, cliPerCog);
    txtPaneClienti.setText("Elenco clienti il cui cognome / ragione sociale inizia per : " + cliCog);
    //cerca le fatture da cod cliente
    resetTable(modelFatture);
    fattPerCliCog.clear();
    for (Cliente c : cliPerCog)
    fattPerCliCog.addAll(fatturaDAO.selectFatturaPerCliente(c));
    scanFatture(modelFatture,fattPerCliCog);
    txtPaneFattura.setText("Elenco fatture relative a clienti il cui cognome / ragione sociale inizia per : " + cliCog);
    //cerca le opere dall'iniziale 
    resetTable(modelOpere);
    operePerCliCog.clear();
    for (Fattura f : fattPerCliCog)
    operePerCliCog.addAll(f.getOpere());
    scanOpere(modelOpere, operePerCliCog);
    txtPaneOpere.setText("Elenco opere acquistate da clienti il cui cognome / rag sociale inizia per : " + cliCog);
 
    }
    
}//GEN-LAST:event_buttClienteCogActionPerformed

private void buttClienteRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttClienteRegMouseEntered
    // TODO add your handling code here:
}//GEN-LAST:event_buttClienteRegMouseEntered

private void buttClienteRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttClienteRegActionPerformed
    if(!regioniSel.isEmpty()){
    cliPerReg = clienteDAO.selectClientiPerRegione(regioniSel);
    resetTable(modelCli);
    scanClienti(modelCli, cliPerReg);
    txtPaneClienti.setText("Elenco clienti residenti in: " + regioniSel.toString());
    lModel.clear();
    regioniSel.clear();}
    //cerca le fatture da cod cliente
    resetTable(modelFatture);
    fattPerCliReg.clear();
    for (Cliente c : cliPerReg)
    fattPerCliReg.addAll(fatturaDAO.selectFatturaPerCliente(c));
    scanFatture(modelFatture,fattPerCliReg);
    txtPaneFattura.setText("Elenco fatture relative a clienti residenti in : " + regioniSel.toString());
    //cerca le opere dall'iniziale 
    resetTable(modelOpere);
    operePerCliReg.clear();
    for (Fattura f : fattPerCliReg)
    operePerCliReg.addAll(f.getOpere());
    scanOpere(modelOpere, operePerCliReg);
    txtPaneOpere.setText("Elenco opere acquistate da clienti residenti in : " + regioniSel.toString());
 
    
}//GEN-LAST:event_buttClienteRegActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    
}//GEN-LAST:event_jComboBox1ActionPerformed

private void buttClienteRegAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttClienteRegAddMouseEntered
    // TODO add your handling code here:
}//GEN-LAST:event_buttClienteRegAddMouseEntered

private void buttClienteRegAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttClienteRegAddActionPerformed
    Regione regSel = (Regione) jComboBox1.getSelectedItem();
    if(!regioniSel.contains(regSel)){
    regioniSel.add(regSel);
    lModel.addElement((Object)regSel);}
    listRegSel.setModel(lModel);
}//GEN-LAST:event_buttClienteRegAddActionPerformed

private void buttClienteRegDelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttClienteRegDelMouseEntered

}//GEN-LAST:event_buttClienteRegDelMouseEntered

private void buttClienteRegDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttClienteRegDelActionPerformed
    Object oDel=listRegSel.getSelectedValue();
    regioniSel.remove(oDel);
    lModel.removeElement(oDel);
    listRegSel.setModel(lModel);
}//GEN-LAST:event_buttClienteRegDelActionPerformed

private void txtFatturaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFatturaCodActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtFatturaCodActionPerformed

private void buttFatturaCodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttFatturaCodMouseEntered
    // TODO add your handling code here:
}//GEN-LAST:event_buttFatturaCodMouseEntered

private void buttFatturaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttFatturaCodActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_buttFatturaCodActionPerformed

private void buttonResFattureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResFattureActionPerformed
    
}//GEN-LAST:event_buttonResFattureActionPerformed

private void buttonResAllArtista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResAllArtista1ActionPerformed
    resAll();
}//GEN-LAST:event_buttonResAllArtista1ActionPerformed

private void buttFatturaCod1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttFatturaCod1MouseEntered
    // TODO add your handling code here:
}//GEN-LAST:event_buttFatturaCod1MouseEntered

private void buttFatturaCod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttFatturaCod1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_buttFatturaCod1ActionPerformed

private void txtFatturaCod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFatturaCod1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtFatturaCod1ActionPerformed

private void buttFatturaCod2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttFatturaCod2MouseEntered
    // TODO add your handling code here:
}//GEN-LAST:event_buttFatturaCod2MouseEntered

private void buttFatturaCod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttFatturaCod2ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_buttFatturaCod2ActionPerformed

private void txtFatturaCod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFatturaCod2ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtFatturaCod2ActionPerformed

//funzione per popolare la tabella del tab clienti

    public void fillTabCli() {
        Vector<Cliente> c = clienteDAO.findAllClienti();
        scanClienti(modelCli, c);
        jTable1.setModel(modelCli);
    }

    public void fillTabOpere() {
        Vector<Opera> o = operaDAO.findAllOpere();
        scanOpere(modelOpere, o);
        jTable2.setModel(modelOpere);
    }

    public void fillTabArtisti() {
        Vector<Artista> a = artistaDAO.findAllArtisti();
        scanArtisti(modelArtisti, a);
        jTable3.setModel(modelArtisti);
    }
    
    public void fillTabFatture() {
        Vector<Fattura> a = fatturaDAO.findAllFatture();
        scanFatture(modelFatture, a);
        jTable4.setModel(modelFatture);
    }

    void fillColonne(DefaultTableModel t, String[] c) {
        for (int i = 0; i < c.length; i++) {
            t.addColumn(c[i]);
        }
    }

    void scanArtisti(DefaultTableModel t, Vector<Artista> a) {
        Iterator it = a.iterator();
        while (it.hasNext()) {
            Artista art = (Artista) it.next();
            createRowArtisti(t, art);
        }
    }

    void scanOpere(DefaultTableModel t, Vector<Opera> o) {
        Iterator it = o.iterator();
        while (it.hasNext()) {
            Opera op = (Opera) it.next();
            createRowOpere(t, op);
        }
    }

    void scanClienti(DefaultTableModel t, Vector<Cliente> c) {
        Iterator it = c.iterator();
        while (it.hasNext()) {
            Cliente r = (Cliente) it.next();
            createRowClienti(t, r);
        }
    }

    void createRowClienti(DefaultTableModel t, Cliente r) {
        Object[] s = {r.getCodiceCliente(), r.getCognRsoc1(), r.getNomeRsoc2(), r.getIndirizzo(), r.getNCiv(), r.getCitta(), r.getProvincia(), r.getRegione(), r.getStato(), r.getTel1(), r.getTel2(), r.getCell1(), r.getCell2(), r.getMail1(), r.getMail2(), r.getCfPiva(), r.getNote()};
        t.addRow(s);
    }

    void createRowOpere(DefaultTableModel t, Opera op) {
        //Object[] s = {op.getCodiceOpera(), op.getTitolo(), op.getArtista().getCognome()+ " " +op.getArtista().getNome(), op.getTecnica(), op.getDimensioni(), op.getTipo(), op.isVenduto(), op.getFoto(), op.getFattura().getNumeroFattura(), op.getPrezzo()};
        //t.addRow(s);
    }

    void createRowArtisti(DefaultTableModel t, Artista art) {
        Object[] s = {art.getCodiceArtista(), art.getCognome(), art.getNome(), art.getNoteBiografiche()};
        t.addRow(s);
    }
    
    void createRowFatture(DefaultTableModel t, Fattura fatt) {
        Object[] s = {fatt.getNumeroFattura(),fatt.getCliente().getCognRsoc1() +" "+fatt.getCliente().getNomeRsoc2(),fatt.getDataFattura(),fatt.getSconto(),fatt.getTotale()};
        t.addRow(s);
    }
    
    void scanFatture (DefaultTableModel t, Vector<Fattura> fatture){       
        Iterator it = fatture.iterator();
        while (it.hasNext()) {
            Fattura fattura = (Fattura) it.next();
            createRowFatture(t, fattura);
        }
    }

    void resetTable(DefaultTableModel t) {
        int j = t.getRowCount();
        for (int k = 0; k < j; k++) {
            t.removeRow(0);
        }
    }
    
    void resAll(){
    resetTable(modelCli);
    resetTable(modelArtisti);
    resetTable(modelOpere);
    resetTable(modelFatture);
    fillTabCli();
    fillTabOpere();
    fillTabArtisti();
    fillTabFatture();
    txtPaneArtisti.setText("Elenco completo artisti");
    txtPaneClienti.setText("Elenco completo clienti");
    txtPaneOpere.setText("Elenco completo opere");
    txtPaneFattura.setText("Elenco completo fatture");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttArtistaCod;
    private javax.swing.JButton buttClienteCog;
    private javax.swing.JButton buttClienteReg;
    private javax.swing.JButton buttClienteRegAdd;
    private javax.swing.JButton buttClienteRegDel;
    private javax.swing.JButton buttFatturaCod;
    private javax.swing.JButton buttFatturaCod1;
    private javax.swing.JButton buttFatturaCod2;
    private javax.swing.JButton buttOperaCod;
    private javax.swing.JButton buttonResAllArtista;
    private javax.swing.JButton buttonResAllArtista1;
    private javax.swing.JButton buttonResAllClienti;
    private javax.swing.JButton buttonResAllOpere;
    private javax.swing.JButton buttonResArtista;
    private javax.swing.JButton buttonResClienti;
    private javax.swing.JButton buttonResFatture;
    private javax.swing.JButton buttonResOpere;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JList listRegSel;
    private javax.swing.JTextField txtArtistaCod;
    private javax.swing.JTextField txtCogCod;
    private javax.swing.JTextField txtFatturaCod;
    private javax.swing.JTextField txtFatturaCod1;
    private javax.swing.JTextField txtFatturaCod2;
    private javax.swing.JTextField txtOperaCod;
    private javax.swing.JTextPane txtPaneArtisti;
    private javax.swing.JTextPane txtPaneClienti;
    private javax.swing.JTextPane txtPaneFattura;
    private javax.swing.JTextPane txtPaneOpere;
    // End of variables declaration//GEN-END:variables
}
